# see https://hugomods.com/en/docs/google-analytics/.
# googleAnalytics: 'G-XXXXXXXXXX' # Google Analytics, please make sure you've imported the Google Analytics module.
googleAnalytics: 'G-32CMLL55HH'
# disqusShortname: XXXXXX # The Disqus shortname.

params:
  # google_adsense: 